### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $ionicUserProvider <- $ionicUser <- DashCtrl after following tutorial through twice.

### ISSUE THREAD

**Issue by bobbyfisher928** [driftyco/ionic-push-tutorial-app#2]
Error: [$injector:unpr] Unknown provider: $ionicUserProvider <- $ionicUser <- DashCtrl
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=NaNonicUserProvider%20%3C-%20%24ionicUser%20%3C-%20DashCtrl
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:8762:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12696:19
    at Object.getService [as get] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12843:39)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12701:45
    at getService (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12843:39)
    at invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12875:13)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12892:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17161:28
    at self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:48253:24)
    at Object.switcher.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:46450:41)(anonymous function) @ ionic.bundle.js:20306
ionic.bundle.js:20306 Error: [$injector:unpr] Unknown provider: $ionicUserProvider <- $ionicUser <- DashCtrl
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=NaNonicUserProvider%20%3C-%20%24ionicUser%20%3C-%20DashCtrl
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:8762:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12696:19
    at Object.getService [as get] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12843:39)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12701:45
    at getService (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12843:39)
    at invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12875:13)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12892:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17161:28
    at self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:48253:24)
    at Object.switcher.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:46450:41)

I have followed the tutorial completely through twice. Both times I double checked that all my files matched. I was wondering if someone could help me understand what I may be missing so I can figure out what I did wrong.

**Comment by sinanulkuatam** [comment]
@bobbyfisher928 I included these dependencies in order to get it running (in addition to injecting 'ionic' into my app module)
 
'ionic.service.core',
'ionic.service.push'

@Fuiste I believe this step can be added to the tutorial to prevent further confusion.

**Comment by Fuiste** [comment]
Injecting `ionic.service.core

**Comment by Fuiste** [comment]
@sinanulkuatam injecting `ionic.service.core` and `ionic.service.push` into the app module should no longer be necessary in the latest version of the CLI, as it will automatically do this for you.

**Comment by sinanulkuatam** [comment]
@Fuiste could be why it didn't inject properly for me either, as I have a separate project structure than the default app.  Ran into this error when running 'ionic add ionic-service-push' so I added the dependency manually, thanks for clearing up the confusion.

ERROR:  { [Error: ENOENT, open './www/js/app.js'] errno: 34, code: 'ENOENT', path: './www/js/app.js' }
Is your app declaration contained in 'app.js'?

**Comment by Fuiste** [comment]
@sinanulkuatam you can check out the docs [here](http://docs.ionic.io/v1.0/docs/io-service-modules#section-modifications) for info on what modificatinos are happening, as well as how to disable them in the case where you have a non-standard app structure.

**Comment by sinanulkuatam** [comment]
Very useful, thanks!
